export const PLUGIN_MAP: Record<string, string> = {
	"@eslint-react": "@elsikora/react/1",
	"@eslint-react/dom": "@elsikora/react/1/dom",
	"@eslint-react/hooks-extra": "@elsikora/react/1/hooks-extra",
	"@eslint-react/naming-convention": "@elsikora/react/1/naming-convention",
	"@eslint-react/web-api": "@elsikora/react/1/web-api",
	"@next/next": "@elsikora/next",
	"@stylistic": "@elsikora-stylistic",
	"@typescript-eslint": "@elsikora-typescript",
	"check-file": "@elsikora-check-file",
	css: "@elsikora/css",
	jsdoc: "@elsikora-jsdoc",
	jsonc: "elsikora-json",
	"jsx-a11y": "@elsikora/jsx",
	markdown: "@elsikora/markdown",
	n: "elsikora-node",
	"package-json": "@elsikora-package-json",
	perfectionist: "@elsikora-perfectionist",
	prettier: "@elsikora-prettier",
	react: "@elsikora/react/2",
	sonarjs: "@elsikora-sonar",
	unicorn: "@elsikora-unicorn",
};

export default PLUGIN_MAP;
