export const PLUGIN_MAP: Record<string, string> = {
	"@conarti/feature-sliced": "@elsikora/fsd",
	"@eslint-react": "@elsikora/react/1",
	"@eslint-react/dom": "@elsikora/react/1/dom",
	"@eslint-react/hooks-extra": "@elsikora/react/1/hooks-extra",
	"@eslint-react/naming-convention": "@elsikora/react/1/naming-convention",
	"@eslint-react/web-api": "@elsikora/react/1/web-api",
	"@next/next": "@elsikora/next",
	"@stylistic": "@elsikora/stylistic",
	"@tanstack/query": "@elsikora/tanstack/query",
	"@tanstack/router": "@elsikora/tanstack/router",
	"@typescript-eslint": "@elsikora/typescript",
	"check-file": "@elsikora/check-file",
	css: "@elsikora/css",
	i18next: "@elsikora/i18next",
	jsdoc: "@elsikora/jsdoc",
	jsonc: "@elsikora/json",
	"jsonc/vue-custom-block": "@elsikora/json/vue-custom-block",
	"jsx-a11y": "@elsikora/jsx",
	markdown: "@elsikora/markdown",
	n: "@elsikora/node",
	"n/no-unsupported-features": "@elsikora/node/no-unsupported-features",
	"nestjs-typed": "@elsikora/nest/2",
	"ng-module-sort": "@elsikora/nest/1",
	"no-secrets": "@elsikora/no-secrets",
	"package-json": "@elsikora/package-json",
	perfectionist: "@elsikora/perfectionist",
	prettier: "@elsikora/prettier",
	react: "@elsikora/react/2",
	sonarjs: "@elsikora/sonar",
	storybook: "@elsikora/storybook",
	tailwindcss: "@elsikora/tailwindcss",
	unicorn: "@elsikora/unicorn",
};

export default PLUGIN_MAP;
