export interface IConfigOptions {
	withCheckFile?: boolean;
	withCss?: boolean;
	withFsd?: boolean;
	withI18next?: boolean;
	withJavascript?: boolean;
	withJsDoc?: boolean;
	withJson?: boolean;
	withJsx?: boolean;
	withMarkdown?: boolean;
	withNest?: boolean;
	withNext?: boolean;
	withNode?: boolean;
	withNoSecrets?: boolean;
	withPackageJson?: boolean;
	withPerfectionist?: boolean;
	withPrettier?: boolean;
	withReact?: boolean;
	withRegexp?: boolean;
	withSonar?: boolean;
	withStorybook?: boolean;
	withStylistic?: boolean;
	withTailwindCss?: boolean;
	withTanstack?: boolean;
	withTypeorm?: boolean;
	withTypescript?: boolean;
	withUnicorn?: boolean;
	withYaml?: boolean;
}
