import type { IConfigOptions } from "../../../dist/esm/index";

import type { IRuleBehaviorScenario } from "./types";

export const ALL_CONFIG_OPTIONS: Required<IConfigOptions> = {
	withCheckFile: true,
	withCss: true,
	withFsd: true,
	withI18next: true,
	withJavascript: true,
	withJsDoc: true,
	withJson: true,
	withJsx: true,
	withMarkdown: true,
	withNest: true,
	withNext: true,
	withNode: true,
	withNoSecrets: true,
	withPackageJson: true,
	withPerfectionist: true,
	withPrettier: true,
	withReact: true,
	withRegexp: true,
	withSonar: true,
	withStorybook: true,
	withStylistic: true,
	withTailwindCss: true,
	withTanstack: true,
	withTypeorm: true,
	withTypescript: true,
	withTypescriptStrict: true,
	withUnicorn: true,
	withYaml: true,
};

export const RULE_BEHAVIOR_SCENARIOS: Array<IRuleBehaviorScenario> = [
	createScenario("check-file", { withCheckFile: true }),
	createScenario("css", { withCss: true }),
	createScenario("fsd", { withFsd: true }),
	createScenario("i18next", { withI18next: true }),
	createScenario("javascript", { withJavascript: true }),
	createScenario("jsdoc", { withJsDoc: true }),
	createScenario("json", { withJson: true }),
	createScenario("jsx", { withJsx: true }),
	createScenario("markdown", { withMarkdown: true }),
	createScenario("nest", { withNest: true }),
	createScenario("next", { withNext: true }),
	createScenario("node", { withNode: true }),
	createScenario("no-secrets", { withNoSecrets: true }),
	createScenario("package-json", { withPackageJson: true }),
	createScenario("perfectionist", { withPerfectionist: true }),
	createScenario("prettier", { withPrettier: true }),
	createScenario("react", { withReact: true }),
	createScenario("regexp", { withRegexp: true }),
	createScenario("sonar", { withSonar: true }),
	createScenario("storybook", { withStorybook: true }),
	createScenario("stylistic", { withStylistic: true }),
	createScenario("tailwind-css", { withTailwindCss: true }),
	createScenario("tanstack", { withTanstack: true }),
	createScenario("typeorm", { withTypeorm: true }),
	createScenario("typescript", { withTypescript: true }),
	createScenario("typescript-strict", { withTypescriptStrict: true }),
	createScenario("unicorn", { withUnicorn: true }),
	createScenario("yaml", { withYaml: true }),
	createScenario("javascript-with-sonar", { withJavascript: true, withSonar: true }),
	createScenario("node-with-unicorn", { withNode: true, withUnicorn: true }),
	createScenario("typescript-with-unicorn", { withTypescript: true, withUnicorn: true }),
	createScenario("typescript-strict-with-unicorn", { withTypescriptStrict: true, withUnicorn: true }),
	createScenario("perfectionist-with-fsd", { withFsd: true, withPerfectionist: true }),
	createScenario("all-options", ALL_CONFIG_OPTIONS),
];

function createScenario(id: string, options: IConfigOptions): IRuleBehaviorScenario {
	return { id, options };
}
