import type { IRuleBehaviorCase } from "../types";
import { createCase } from "../case-factory";

export const RULE_BEHAVIOR_JSON_CASES: Array<IRuleBehaviorCase> = [
	createCase("json", "@elsikora/json/comma-dangle", { withJson: true }, "test/e2e/fixture/json/invalid/comma-dangle.fixture.json", `{\n\t"a": 1,\n}\n`),
	createCase("json", "@elsikora/json/no-bigint-literals", { withJson: true }, "test/e2e/fixture/json/invalid/no-bigint-literals.fixture.json5", `{\n\t"a": 1n\n}\n`),
	createCase("json", "@elsikora/json/no-binary-expression", { withJson: true }, "test/e2e/fixture/json/invalid/no-binary-expression.fixture.json5", `{\n\t"a": 1 + 2\n}\n`),
	createCase("json", "@elsikora/json/no-binary-numeric-literals", { withJson: true }, "test/e2e/fixture/json/invalid/no-binary-numeric-literals.fixture.json5", `{\n\t"a": 0b10\n}\n`),
	createCase("json", "@elsikora/json/no-comments", { withJson: true }, "test/e2e/fixture/json/invalid/no-comments.fixture.jsonc", `// comment\n{\n\t"a": 1\n}\n`),
	createCase("json", "@elsikora/json/no-dupe-keys", { withJson: true }, "test/e2e/fixture/json/invalid/no-dupe-keys.fixture.json", `{\n\t"a": 1,\n\t"a": 2\n}\n`),
	createCase("json", "@elsikora/json/no-escape-sequence-in-identifier", { withJson: true }, "test/e2e/fixture/json/invalid/no-escape-sequence-in-identifier.fixture.json5", `{\n\t\\u0061: 1\n}\n`),
	createCase("json", "@elsikora/json/no-floating-decimal", { withJson: true }, "test/e2e/fixture/json/invalid/no-floating-decimal.fixture.json5", `{\n\t"a": .5\n}\n`),
	createCase("json", "@elsikora/json/no-hexadecimal-numeric-literals", { withJson: true }, "test/e2e/fixture/json/invalid/no-hexadecimal-numeric-literals.fixture.json5", `{\n\t"a": 0x10\n}\n`),
	createCase("json", "@elsikora/json/no-infinity", { withJson: true }, "test/e2e/fixture/json/invalid/no-infinity.fixture.json5", `{\n\t"a": Infinity\n}\n`),
	createCase("json", "@elsikora/json/no-irregular-whitespace", { withJson: true }, "test/e2e/fixture/json/invalid/no-irregular-whitespace.fixture.json", `{\n\t"a": 1,\n\u00a0"b": 2\n}\n`),
	createCase("json", "@elsikora/json/no-multi-str", { withJson: true }, "test/e2e/fixture/json/invalid/no-multi-str.fixture.json5", `{\n\t"a": "line\\\nnext"\n}\n`),
	createCase("json", "@elsikora/json/no-nan", { withJson: true }, "test/e2e/fixture/json/invalid/no-nan.fixture.json5", `{\n\t"a": NaN\n}\n`),
	createCase("json", "@elsikora/json/no-number-props", { withJson: true }, "test/e2e/fixture/json/invalid/no-number-props.fixture.json5", `{\n\t1: "a"\n}\n`),
	createCase("json", "@elsikora/json/no-numeric-separators", { withJson: true }, "test/e2e/fixture/json/invalid/no-numeric-separators.fixture.json5", `{\n\t"a": 1_000\n}\n`),
	createCase("json", "@elsikora/json/no-octal", { withJson: true }, "test/e2e/fixture/json/invalid/no-octal.fixture.json5", `{\n\t"a": 012\n}\n`),
	createCase("json", "@elsikora/json/no-octal-numeric-literals", { withJson: true }, "test/e2e/fixture/json/invalid/no-octal-numeric-literals.fixture.json5", `{\n\t"a": 0o12\n}\n`),
	createCase("json", "@elsikora/json/no-parenthesized", { withJson: true }, "test/e2e/fixture/json/invalid/no-parenthesized.fixture.json5", `{\n\t"a": (1)\n}\n`),
	createCase("json", "@elsikora/json/no-plus-sign", { withJson: true }, "test/e2e/fixture/json/invalid/no-plus-sign.fixture.json5", `{\n\t"a": +1\n}\n`),
	createCase("json", "@elsikora/json/no-regexp-literals", { withJson: true }, "test/e2e/fixture/json/invalid/no-regexp-literals.fixture.json5", `{\n\t"a": /x/u\n}\n`),
	createCase("json", "@elsikora/json/no-sparse-arrays", { withJson: true }, "test/e2e/fixture/json/invalid/no-sparse-arrays.fixture.json5", `[1,,2]\n`),
	createCase("json", "@elsikora/json/no-template-literals", { withJson: true }, "test/e2e/fixture/json/invalid/no-template-literals.fixture.json5", `{\n\t"a": \`value\`\n}\n`),
	createCase("json", "@elsikora/json/no-undefined-value", { withJson: true }, "test/e2e/fixture/json/invalid/no-undefined-value.fixture.json5", `{\n\t"a": undefined\n}\n`),
	createCase("json", "@elsikora/json/no-unicode-codepoint-escapes", { withJson: true }, "test/e2e/fixture/json/invalid/no-unicode-codepoint-escapes.fixture.json5", `{\n\t"\\u{61}": 1\n}\n`),
	createCase("json", "@elsikora/json/no-useless-escape", { withJson: true }, "test/e2e/fixture/json/invalid/no-useless-escape.fixture.json", `{\n\t"a": "\\/"\n}\n`),
	createCase("json", "@elsikora/json/quote-props", { withJson: true }, "test/e2e/fixture/json/invalid/quote-props.fixture.json5", `{\n\ta: 1\n}\n`),
	createCase("json", "@elsikora/json/quotes", { withJson: true }, "test/e2e/fixture/json/invalid/quotes.fixture.json5", `{\n\t"a": 'b'\n}\n`),
	createCase("json", "@elsikora/json/sort-keys", { withJson: true }, "test/e2e/fixture/json/invalid/sort-keys.fixture.json", `{\n\t"b": 1,\n\t"a": 2\n}\n`),
	createCase("json", "@elsikora/json/space-unary-ops", { withJson: true }, "test/e2e/fixture/json/invalid/space-unary-ops.fixture.json5", `{\n\t"a": - 1\n}\n`),
	createCase("json", "@elsikora/json/valid-json-number", { withJson: true }, "test/e2e/fixture/json/invalid/valid-json-number.fixture.json5", `{\n\t"a": 01\n}\n`),
	createCase("json", "@elsikora/json/vue-custom-block/no-parsing-error", { withJson: true }, "test/e2e/fixture/json/valid/no-parsing-error.fixture.json", `{\n\t"a": 1\n}\n`, "not-reported"),
];
