import type { IRuleBehaviorCase } from "../types";
import { createCase, createCases } from "../case-factory";

export const RULE_BEHAVIOR_TYPESCRIPT_CASES: Array<IRuleBehaviorCase> = [
	createCase("typescript", "sort-decorators/sort-on-classes", { withTypescript: true }, "test/e2e/fixture/typescript/invalid/sort-decorators.fixture.ts"),
	createCase("typescript", "sort-decorators/sort-on-accessors", { withTypescript: true }, "test/e2e/fixture/typescript/invalid/sort-decorators.fixture.ts"),
	createCase("typescript", "sort-decorators/sort-on-methods", { withTypescript: true }, "test/e2e/fixture/typescript/invalid/sort-decorators.fixture.ts"),
	createCase("typescript", "sort-decorators/sort-on-parameters", { withTypescript: true }, "test/e2e/fixture/typescript/invalid/sort-decorators.fixture.ts"),
	createCase("typescript", "sort-decorators/sort-on-properties", { withTypescript: true }, "test/e2e/fixture/typescript/invalid/sort-decorators.fixture.ts"),
	...createCases("typescript", { withTypescript: true }, "test/e2e/fixture/typescript/invalid/typescript-syntax-rules.fixture.ts", [
		"@typescript-eslint/array-type",
		"@typescript-eslint/ban-tslint-comment",
		"@typescript-eslint/class-literal-property-style",
		"@typescript-eslint/consistent-generic-constructors",
		"@typescript-eslint/consistent-indexed-object-style",
		"@typescript-eslint/consistent-type-assertions",
		"@typescript-eslint/consistent-type-exports",
		"@typescript-eslint/consistent-type-imports",
		"@typescript-eslint/no-array-constructor",
		"@typescript-eslint/no-duplicate-enum-values",
		"@typescript-eslint/no-duplicate-type-constituents",
		"@typescript-eslint/no-dynamic-delete",
		"@typescript-eslint/no-empty-function",
		"@typescript-eslint/no-empty-interface",
		"@typescript-eslint/no-explicit-any",
		"@typescript-eslint/no-import-type-side-effects",
		"@typescript-eslint/no-invalid-void-type",
		"@typescript-eslint/no-misused-new",
		"@typescript-eslint/no-mixed-enums",
		"@typescript-eslint/no-namespace",
		"@typescript-eslint/no-redeclare",
		"@typescript-eslint/no-redundant-type-constituents",
		"@typescript-eslint/no-require-imports",
		"@typescript-eslint/no-unnecessary-type-arguments",
		"@typescript-eslint/no-unnecessary-type-constraint",
		"@typescript-eslint/no-unsafe-declaration-merging",
		"@typescript-eslint/no-unsafe-function-type",
		"@typescript-eslint/no-unused-expressions",
		"@typescript-eslint/no-useless-constructor",
		"@typescript-eslint/no-useless-empty-export",
		"@typescript-eslint/no-wrapper-object-types",
		"@typescript-eslint/prefer-as-const",
		"@typescript-eslint/prefer-enum-initializers",
		"@typescript-eslint/prefer-function-type",
		"@typescript-eslint/prefer-namespace-keyword",
		"@typescript-eslint/triple-slash-reference",
		"@typescript-eslint/unified-signatures",
		"no-var",
		"prefer-const",
		"prefer-rest-params",
		"prefer-spread",
	]),
	...createCases("typescript", { withTypescript: true }, "test/e2e/fixture/typescript/invalid/typescript-type-aware-rules.fixture.ts", [
		"@typescript-eslint/adjacent-overload-signatures",
		"@typescript-eslint/await-thenable",
		"@typescript-eslint/dot-notation",
		"@typescript-eslint/no-array-delete",
		"@typescript-eslint/no-base-to-string",
		"@typescript-eslint/no-confusing-non-null-assertion",
		"@typescript-eslint/no-confusing-void-expression",
		"@typescript-eslint/no-deprecated",
		"@typescript-eslint/no-extra-non-null-assertion",
		"@typescript-eslint/no-for-in-array",
		"@typescript-eslint/no-implied-eval",
		"@typescript-eslint/no-loop-func",
		"@typescript-eslint/no-meaningless-void-operator",
		"@typescript-eslint/no-misused-promises",
		"@typescript-eslint/no-misused-spread",
		"@typescript-eslint/no-non-null-asserted-nullish-coalescing",
		"@typescript-eslint/no-non-null-asserted-optional-chain",
		"@typescript-eslint/no-non-null-assertion",
		"@typescript-eslint/no-this-alias",
		"@typescript-eslint/no-unnecessary-boolean-literal-compare",
		"@typescript-eslint/no-unnecessary-template-expression",
		"@typescript-eslint/no-unnecessary-type-assertion",
		"@typescript-eslint/no-unnecessary-type-conversion",
		"@typescript-eslint/no-unnecessary-type-parameters",
		"@typescript-eslint/no-unsafe-argument",
		"@typescript-eslint/no-unsafe-assignment",
		"@typescript-eslint/no-unsafe-call",
		"@typescript-eslint/no-unsafe-enum-comparison",
		"@typescript-eslint/no-unsafe-member-access",
		"@typescript-eslint/no-unsafe-return",
		"@typescript-eslint/no-unsafe-unary-minus",
		"@typescript-eslint/no-useless-default-assignment",
		"@typescript-eslint/non-nullable-type-assertion-style",
		"@typescript-eslint/only-throw-error",
		"@typescript-eslint/prefer-find",
		"@typescript-eslint/prefer-for-of",
		"@typescript-eslint/prefer-includes",
		"@typescript-eslint/prefer-nullish-coalescing",
		"@typescript-eslint/prefer-optional-chain",
		"@typescript-eslint/prefer-promise-reject-errors",
		"@typescript-eslint/prefer-readonly",
		"@typescript-eslint/prefer-reduce-type-parameter",
		"@typescript-eslint/prefer-regexp-exec",
		"@typescript-eslint/prefer-return-this-type",
		"@typescript-eslint/prefer-string-starts-ends-with",
		"@typescript-eslint/related-getter-setter-pairs",
		"@typescript-eslint/require-array-sort-compare",
		"@typescript-eslint/require-await",
		"@typescript-eslint/restrict-plus-operands",
		"@typescript-eslint/restrict-template-expressions",
		"@typescript-eslint/return-await",
		"@typescript-eslint/switch-exhaustiveness-check",
		"@typescript-eslint/use-unknown-in-catch-callback-variable",
	]),
	createCase("typescript", "@typescript-eslint/no-restricted-imports", { withTypescript: true }, "test/e2e/fixture/typescript/valid/clean.fixture.ts", undefined, "not-reported"),
	createCase("typescript-strict", "@typescript-eslint/explicit-function-return-type", { withTypescriptStrict: true }, "test/e2e/fixture/typescript/invalid/explicit-function-return-type.fixture.ts"),
	createCase("typescript-strict", "@typescript-eslint/explicit-module-boundary-types", { withTypescriptStrict: true }, "test/e2e/fixture/typescript/invalid/explicit-function-return-type.fixture.ts"),
	createCase("typescript-strict", "@typescript-eslint/naming-convention", { withTypescriptStrict: true }, "test/e2e/fixture/typescript/invalid/naming-convention.fixture.ts"),
	createCase("typescript-strict", "@typescript-eslint/no-magic-numbers", { withTypescriptStrict: true }, "test/e2e/fixture/typescript/invalid/strict-rules.fixture.ts"),
	createCase("typescript-strict", "@typescript-eslint/typedef", { withTypescriptStrict: true }, "test/e2e/fixture/typescript/invalid/strict-rules.fixture.ts"),
	createCase("typescript-strict", "@typescript-eslint/unbound-method", { withTypescriptStrict: true }, "test/e2e/fixture/typescript/invalid/strict-rules.fixture.ts"),
];
